apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    vault.harshicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "tooling-app"
    vault.harshicorp.com/agent-inject-secret-mysqlPassword: "kv2/data/tooling/dev/MYSQL_PASS"
    vault.hashicorp.com/agent-inject-template-helloworld: |
      {{`{{- with secret "kv2/data/tooling/dev/MYSQL_PASS" -}}
      export MYSQL_PASS={{ .Data.data.MYSQL_PASS }}
      {{- end }}`}}
  name: {{ include "tooling.fullname" . }}
  labels:
    {{- include "tooling.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tooling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tooling.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tooling.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: MYSQL_IP
            value: {{ .Values.tooling.mysql_ip }}
          - name: MYSQL_USER
            value: {{ .Values.tooling.mysql_user }}
          {{- if  .Values.tooling.mysql_pass }}
          - name: MYSQL_PASS
            value: {{ .Values.tooling.mysql_pass }}
          {{- end }}
          - name: MYSQL_DBNAME
            value: {{ .Values.tooling.mysql_dbname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
